name: lint-and-test
on:
    push:
        branches: ['main']
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: scan files
              run: npm run lint
    e2e-test:
        timeout-minutes: 3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: install playwright browsers
              run: npx playwright install --with-deps
            - name: run playwright tests
              run: CI=true npm run test:e2e
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
