name: build-and-test
on:
    push:
        branches: ['main']
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm install
            - name: scan files
              run: npm run lint
